"""This file mirrors all the definitions made in the `py-dexter` Rust API."""

from typing import Any, Optional, Literal

from dexter.types import (
    ArrayShape,
    Array1,
    Array2,
    NetCDFVersion,
    EquilibriumType,
    Interp1DType,
    Interp2DType,
    FluxWall,
    FluxState,
    PhaseMethod,
    Intersection,
    IntegrationStatus,
    SteppingMethod,
)

# ================================================================================================

class _PyLarGeometry:
    """PyO3 export of `dexter_equilibrium::LarGeometry`."""

    equilibrium_type: EquilibriumType
    baxis: float
    raxis: float
    rwall: float
    psi_wall: float
    rlab_wall: Array1
    zlab_wall: Array1

    def __init__(self, baxis: float, raxis: float, rwall: float) -> None: ...
    def r_of_psi(self, psi: float) -> float: ...
    def r_of_psip(self, psip: float) -> float: ...
    def psi_of_r(self, r: float) -> float: ...
    def psip_of_r(self, r: float) -> float: ...
    def rlab_of_psi(self, psi: float, theta: float) -> float: ...
    def rlab_of_psip(self, psip: float, theta: float) -> float: ...
    def zlab_of_psi(self, psi: float, theta: float) -> float: ...
    def zlab_of_psip(self, psip: float, theta: float) -> float: ...
    def jacobian_of_psi(self, psi: float, theta: float) -> float: ...
    def jacobian_of_psip(self, psip: float, theta: float) -> float: ...

class _PyNcGeometry:
    """PyO3 export of `dexter_equilibrium::NcGeometry`."""

    path: str
    netcdf_version: NetCDFVersion
    equilibrium_type: EquilibriumType
    interp1d_type: Interp1DType
    interp2d_type: Interp2DType
    baxis: float
    raxis: float
    zaxis: float
    rgeo: float
    rwall: float
    shape: ArrayShape
    psi_wall: float
    psip_wall: float
    psi_state: FluxState
    psip_state: FluxState
    psi_array: Array1
    psip_array: Array1
    theta_array: Array1
    r_array: Array1
    rlab_array: Array2
    zlab_array: Array2
    jacobian_array: Array2
    rlab_wall: Array1
    zlab_wall: Array1

    def __init__(
        self,
        path: str,
        interp1d_type: Interp1DType,
        interp2d_type: Interp2DType,
    ) -> None: ...
    def psip_of_psi(self, psi: float) -> float: ...
    def psi_of_psip(self, psip: float) -> float: ...
    def r_of_psi(self, psi: float) -> float: ...
    def r_of_psip(self, psip: float) -> float: ...
    def psi_of_r(self, r: float) -> float: ...
    def psip_of_r(self, r: float) -> float: ...
    def rlab_of_psi(self, psi: float, theta: float) -> float: ...
    def rlab_of_psip(self, psip: float, theta: float) -> float: ...
    def zlab_of_psi(self, psi: float, theta: float) -> float: ...
    def zlab_of_psip(self, psip: float, theta: float) -> float: ...
    def jacobian_of_psi(self, psi: float, theta: float) -> float: ...
    def jacobian_of_psip(self, psip: float, theta: float) -> float: ...

# ================================================================================================

class _PyUnityQfactor:
    """PyO3 export of `dexter_equilibrium::UnityQfactor`."""

    equilibrium_type: EquilibriumType

    def __init__(self): ...
    def psip_of_psi(self, psi: float) -> float: ...
    def psi_of_psip(self, psip: float) -> float: ...
    def q_of_psi(self, psi: float) -> float: ...
    def q_of_psip(self, psip: float) -> float: ...
    def dpsi_dpsip(self, psip: float) -> float: ...
    def dpsip_dpsi(self, psi: float) -> float: ...
    def iota_of_psi(self, psi: float) -> float: ...
    def iota_of_psip(self, psip: float) -> float: ...

class _PyParabolicQfactor:
    """PyO3 export of `dexter_equilibrium::ParabolicQfactor`."""

    equilibrium_type: EquilibriumType
    qaxis: float
    qwall: float
    psi_wall: float
    psip_wall: float

    def __init__(self, qaxis: float, qwall: float, flux_wall: FluxWall) -> None: ...
    def psip_of_psi(self, psi: float) -> float: ...
    def psi_of_psip(self, psip: float) -> float: ...
    def q_of_psi(self, psi: float) -> float: ...
    def q_of_psip(self, psip: float) -> float: ...
    def dpsi_dpsip(self, psip: float) -> float: ...
    def dpsip_dpsi(self, psi: float) -> float: ...
    def iota_of_psi(self, psi: float) -> float: ...
    def iota_of_psip(self, psip: float) -> float: ...

class _PyNcQfactor:
    """PyO3 export of `dexter_equilibrium::NcQfactor`."""

    path: str
    netcdf_version: NetCDFVersion
    equilibrium_type: EquilibriumType
    interp_type: Interp1DType
    qaxis: float
    qwall: float
    psi_wall: float
    psip_wall: float
    psi_state: FluxState
    psip_state: FluxState
    psi_array: Array1
    psip_array: Array1
    q_array: Array1

    def __init__(self, path: str, interp_type: Interp1DType) -> None: ...
    def psip_of_psi(self, psi: float) -> float: ...
    def psi_of_psip(self, psip: float) -> float: ...
    def q_of_psi(self, psi: float) -> float: ...
    def q_of_psip(self, psip: float) -> float: ...
    def dpsi_dpsip(self, psip: float) -> float: ...
    def dpsip_dpsi(self, psi: float) -> float: ...
    def iota_of_psi(self, psi: float) -> float: ...
    def iota_of_psip(self, psip: float) -> float: ...

# ================================================================================================

class _PyLarCurrent:
    """PyO3 export of `dexter_equilibrium::LarCurrent`."""

    equilibrium_type: EquilibriumType

    def __init__(self) -> None: ...
    def g_of_psi(self, psi: float) -> float: ...
    def g_of_psip(self, psip: float) -> float: ...
    def i_of_psi(self, psi: float) -> float: ...
    def i_of_psip(self, psip: float) -> float: ...
    def dg_dpsi(self, psi: float) -> float: ...
    def dg_dpsip(self, psip: float) -> float: ...
    def di_dpsi(self, psi: float) -> float: ...
    def di_dpsip(self, psip: float) -> float: ...

class _PyNcCurrent:
    """PyO3 export of `dexter_equilibrium::NcCurrent`."""

    path: str
    netcdf_version: NetCDFVersion
    equilibrium_type: EquilibriumType
    interp_type: Interp1DType
    psi_wall: float
    psip_wall: float
    psi_state: FluxState
    psip_state: FluxState
    psi_array: Array1
    psip_array: Array1
    g_array: Array1
    i_array: Array1

    def __init__(self, path: str, interp_type: Interp1DType) -> None: ...
    def g_of_psi(self, psi: float) -> float: ...
    def g_of_psip(self, psip: float) -> float: ...
    def i_of_psi(self, psi: float) -> float: ...
    def i_of_psip(self, psip: float) -> float: ...
    def dg_dpsi(self, psi: float) -> float: ...
    def dg_dpsip(self, psip: float) -> float: ...
    def di_dpsi(self, psi: float) -> float: ...
    def di_dpsip(self, psip: float) -> float: ...

# ================================================================================================

class _PyLarBfield:
    """PyO3 export of `dexter_equilibrium::LarBfield`."""

    equilibrium_type: EquilibriumType

    def __init__(self) -> None: ...
    def b_of_psi(self, psi: float, theta: float) -> float: ...
    def b_of_psip(self, psip: float, theta: float) -> float: ...
    def db_dpsi(self, psi: float, theta: float) -> float: ...
    def db_dpsip(self, psip: float, theta: float) -> float: ...
    def db_of_psi_dtheta(self, psi: float, theta: float) -> float: ...
    def db_of_psip_dtheta(self, psip: float, theta: float) -> float: ...

class _PyNcBfield:
    """PyO3 export of `dexter_equilibrium::NcBfield`."""

    path: str
    netcdf_version: NetCDFVersion
    equilibrium_type: EquilibriumType
    interp_type: Interp1DType
    baxis: float
    shape: ArrayShape
    psi_wall: float
    psip_wall: float
    psi_state: FluxState
    psip_state: FluxState
    psi_array: Array1
    psip_array: Array1
    theta_array: Array1
    b_array: Array2

    def __init__(
        self,
        path: str,
        interp_type: Interp2DType,
    ) -> None: ...
    def b_of_psi(self, psi: float, theta: float) -> float: ...
    def b_of_psip(self, psip: float, theta: float) -> float: ...
    def db_dpsi(self, psi: float, theta: float) -> float: ...
    def db_dpsip(self, psip: float, theta: float) -> float: ...
    def db_of_psi_dtheta(self, psi: float, theta: float) -> float: ...
    def db_of_psip_dtheta(self, psip: float, theta: float) -> float: ...

# ================================================================================================

class _PyCosHarmonic:
    """PyO3 export of `dexter_equilibrium::CosHarmonic`."""

    equilibrium_type: EquilibriumType
    alpha: float
    phase: float
    m: int
    n: int

    def __init__(self, alpha: float, m: int, n: int, phase: float) -> None: ...
    # fmt: off
    def alpha_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def alpha_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def phase_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def phase_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def h_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def h_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_dpsi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_dpsip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psi_dtheta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psip_dtheta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psi_dzeta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psip_dzeta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psi_dt(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psip_dt(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    # fmt: on

class _PyNcHarmonic:
    """PyO3 export of `dexter_equilibrium::NcHarmonic`."""

    path: str
    netcdf_version: NetCDFVersion
    equilibrium_type: EquilibriumType
    interp_type: Interp1DType
    m: int
    n: int
    phase_method: PhaseMethod
    phase_average: float
    psi_phase_resonance: float
    psip_phase_resonance: float
    psi_wall: float
    psip_wall: float
    psi_state: FluxState
    psip_state: FluxState
    psi_array: Array1
    psip_array: Array1
    alpha_array: Array1
    phase_array: Array1

    def __init__(
        self,
        path: str,
        interp_type: Interp1DType,
        m: int,
        n: int,
        phase_method: PhaseMethod = "Zero",
    ) -> None: ...
    # fmt: off
    def alpha_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def alpha_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def phase_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def phase_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def h_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def h_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_dpsi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_dpsip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psi_dtheta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psip_dtheta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psi_dzeta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psip_dzeta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psi_dt(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dh_of_psip_dt(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    # fmt: on

# ================================================================================================

class _PyCosPerturbation:
    """PyO3 export of `dexter_equilibrium::Perturbation<CosHarmonic>`."""

    harmonics: list[_PyCosHarmonic]

    def __init__(self, harmonics: list[_PyCosHarmonic]) -> None: ...
    # fmt: off
    def p_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def p_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_dpsi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_dpsip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dtheta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dtheta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dzeta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dzeta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dt(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dt(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def __getitem__(self, index: int): ...
    def __len__(self) -> int: ...
    # fmt: on

class _PyNcPerturbation:
    """PyO3 export of `dexter_equilibrium::Perturbation<NcHarmonic>`."""

    harmonics: list[_PyNcHarmonic]

    def __init__(self, harmonics: list[_PyNcHarmonic]) -> None: ...
    # fmt: off
    def p_of_psi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def p_of_psip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_dpsi(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_dpsip(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dtheta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dtheta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dzeta(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dzeta(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psi_dt(self, psi: float, theta: float, zeta: float, t: float) -> float: ...
    def dp_of_psip_dt(self, psip: float, theta: float, zeta: float, t: float) -> float: ...
    def __getitem__(self, index: int): ...
    def __len__(self) -> int: ...
    # fmt: on

# ================================================================================================
# ================================================================================================

class _PyInitialFlux:
    """PyO3 export of `dexter_simulate::InitialFlux`."""

    kind: Literal["Toroidal", "Poloidal"]
    value: float

    def __init__(self, kind: Literal["Toroidal", "Poloidal"], value: float) -> None: ...

class _PyInitialConditions:
    """PyO3 export of `dexter_simulate::InitialConditions`."""

    t0: float
    flux0: Any
    theta0: float
    zeta0: float
    rho0: float
    mu0: float

    def __init__(
        self,
        t0: float,
        flux0: Any,
        theta0: float,
        zeta0: float,
        rho0: float,
        mu0: float,
    ): ...

class _PyIntersectParams:
    """PyO3 export of `dexter_simulate::IntersectParams`."""

    intersection: Intersection
    angle: float
    turns: int

    def __init__(
        self,
        intersection: Intersection,
        angle: float,
        turns: int,
    ) -> None: ...

class _PyParticle:
    """PyO3 export of `dexter_simulate::Particle`."""

    # Some types are not defined yet, so annotate with `Any`.

    initial_conditions: Any
    integration_status: IntegrationStatus
    steps_taken: int
    steps_stored: int
    initial_energy: float | None
    final_energy: float | None
    energy_var: float | None
    t_array: Array1
    psi_array: Array1
    psip_array: Array1
    theta_array: Array1
    zeta_array: Array1
    rho_array: Array1
    mu_array: Array1
    ptheta_array: Array1
    pzeta_array: Array1
    energy_array: Array1

    def __init__(self, initial_conditions: Any) -> None: ...
    def integrate(
        self,
        /,
        qfactor: Any,
        current: Any,
        bfield: Any,
        perturbation: Any,
        teval: tuple[float, float],
        *,
        stepping_method: Optional[SteppingMethod],
        max_steps: Optional[int],
        first_step: Optional[float],
        safety_factor: Optional[float],
        energy_rel_tol: Optional[float],
        energy_abs_tol: Optional[float],
        error_rel_tol: Optional[float],
        error_abs_tol: Optional[float],
    ): ...
    def intersect(
        self,
        /,
        qfactor: Any,
        current: Any,
        bfield: Any,
        perturbation: Any,
        intersect_params: Any,
        *,
        stepping_method: Optional[SteppingMethod],
        max_steps: Optional[int],
        first_step: Optional[float],
        safety_factor: Optional[float],
        energy_rel_tol: Optional[float],
        energy_abs_tol: Optional[float],
        error_rel_tol: Optional[float],
        error_abs_tol: Optional[float],
    ): ...
