[test]
name = "DEXTER"
manifest-path = "./Cargo.toml"
force-clean = false
skip-clean = true
output-dir = "./htmlcov/"
exclude-files = ["py-dexter/*", "crates/dexter-simulate/bin/*"]
out = ["Html"]
no-fail-fast = true
ignore-panics = true
fail-immediately = true
color = "Always"
engine = "Llvm"
