site_name: DEXTER Documentation
repo_url: https://github.com/George-Tsiamasiotis/DEXTER
repo_name: DEXTER
site_author: George Tsiamasiotis
docs_dir: docs
plugins:
- search:
- mkdocstrings:
    handlers:
      python:
        options:
          # general
          show_bases: false
          show_inheritance_diagram: false
          show_source: false
          # headings
          show_root_heading: true
          show_root_members_full_path: false
          show_object_full_path: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          type_parameter_headings: true
          # docstrings
          docstring_style: numpy
          docstring_section_style: list
          inherited_members: true
          docstring_options:
            ignore_init_summary: false
            trim_doctest_flags: true
          merge_init_into_class: true
          members_order: source
          # Signatures
          annotations_path: source
          modernize_annotations: false
          show_signature_annotations: true
          signature_crossrefs: true
          unwrap_annotated: true
          # Members
          show_labels: true
          summary:
            functions: true
            attributes: true

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.path
    - navigation.top
    - navigation.sections
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  # Math
  - pymdownx.arithmatex:
      generic: true
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - abbr
  - attr_list
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - NetCDF: netcdf.md
  - Scripts: scripts.md
  - API Reference:
    - Types: reference/types.md
    - Equilibrium:
      - Equilibrium: reference/equilibrium/equilibrium.md
      - LarGeometry: reference/equilibrium/lar_geometry.md
      - NcGeometry: reference/equilibrium/nc_geometry.md
      - UnityQfactor: reference/equilibrium/unity_qfactor.md
      - ParabolicQfactor: reference/equilibrium/parabolic_qfactor.md
      - NcQfactor: reference/equilibrium/nc_qfactor.md
      - LarCurrent: reference/equilibrium/lar_current.md
      - NcCurrent: reference/equilibrium/nc_current.md
      - LarBfield: reference/equilibrium/lar_bfield.md
      - NcBfield: reference/equilibrium/nc_bfield.md
      - CosHarmonic: reference/equilibrium/cos_harmonic.md
      - NcHarmonic: reference/equilibrium/nc_harmonic.md
      - Perturbation: reference/equilibrium/perturbation.md
      - Helpers: reference/equilibrium/helpers.md
    - Simulate:
      - Particle: reference/simulate/particle.md
      - Queue: reference/simulate/queue.md
